// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PixPro.Services.Projects.Infrastructure.Persistence;

#nullable disable

namespace PixPro.Services.Projects.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectsDbContext))]
    [Migration("20260610143323_MigrateModelTierEnumValues")]
    partial class MigrateModelTierEnumValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PixPro.Services.Projects.Domain.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("cloudinary_public_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("format");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<Guid?>("OriginalImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_image_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("SecureUrl")
                        .IsRequired()
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("secure_url");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("OriginalImageId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProjectId");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("PixPro.Services.Projects.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("PixPro.Services.Projects.Domain.Entities.UserCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CreditsRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("credits_remaining");

                    b.Property<int>("CreditsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("credits_total");

                    b.Property<string>("ModelTier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_tier");

                    b.Property<DateTimeOffset?>("ResetAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reset_at");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subscription_tier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ModelTier")
                        .IsUnique();

                    b.ToTable("user_credits", (string)null);
                });

            modelBuilder.Entity("PixPro.Services.Projects.Domain.Entities.Image", b =>
                {
                    b.HasOne("PixPro.Services.Projects.Domain.Entities.Project", "Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixPro.Services.Projects.Domain.Entities.Project", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
